const verse16 = {
    slug: "verse-16",

    title: "Verse 16: कटितटपीत",

    description: "16. Maa Durga - Lay all at Her feet—joy and pain alike. Be Meru in stillness, elephant in strength.",

    sanskrit: `
        कटितटपीत दुकूलविचित्र मयुखतिरस्कृत चन्द्ररुचे
        प्रणतसुरासुर मौलिमणिस्फुर दंशुलसन्नख चन्द्ररुचे
        जितकनकाचल मौलिमदोर्जित निर्भरकुञ्जर कुम्भकुचे
        जय जय हे महिषासुरमर्दिनि रम्यकपर्दिनि शैलसुते ॥ १६ ॥

    `,

    meaning: [
        "<strong>16.1:</strong> O Divine Mother, You are wrapped around Your waist in a <span class='highlight' data-sanskrit='कटितटपीतदुकूल'>fine yellow silk sari</span> which is <span class='highlight' data-sanskrit='विचित्र'>wondrously and intricately embroidered</span>; the brilliant <span class='highlight' data-sanskrit='मयुखतिरस्कृत'>blazing rays of light radiating from it completely eclipse</span> and throw into the shade <span class='highlight' data-sanskrit='चन्द्ररुचे'>the pristine luster and beauty of the moon</span>!",


        "<strong>16.2:</strong> O Divine Mother, both <span class='highlight' data-sanskrit='प्रणतसुरासुर'>gods and demons bow down in deep reverence</span> before You; the <span class='highlight' data-sanskrit='मौलिमणिस्फुरदंशु'>gems of their crowns flash and reflect vivid rays of light</span> upon the <span class='highlight' data-sanskrit='लसन्नखचन्द्ररुचे'>beautifully shining nails of Your feet, which radiate like pristine crescent moons</span>!",

        "<strong>16.3:</strong> O Divine Mother, Your majestic form surpasses the <span class='highlight' data-sanskrit='जितकनकचलमौलि'>grandeur of the golden peaks of Mount Meru</span>,and You overflow with a <span class='highlight' data-sanskrit='मदोर्जितनिर्भर'>mighty, unrestrained vital force</span>, radiating the ultimate <span class='highlight' data-sanskrit='कुञ्जरकुम्भकुचे'>abundance and unshakeable power of a majestic royal elephant</span>!",

        "<strong>16.4:</strong> O Divine Mother <span class='highlight' data-sanskrit='जय जय हे महिषासुरमर्दिनि'> Victory, victory to You, O Slayer of Mahishasura </span>, <span class='highlight' data-sanskrit='रम्यकपर्दिनि'> O Beautiful-haired One </span>, <span class='highlight' data-sanskrit='शैलसुते'> O Daughter of the Mountain (Parvati) </span>. <br />"

    ],


    symbols: [

        "[HEADER]  कटितटपीतदुकूलविचित्रमयुखतिरस्कृतचन्द्ररुचे —  The Trap: When Mauna behaves incorrectly, an unpurified seeker's lower energy centers either shrink in fear/victimhood or flare up in aggressive counter-attack. The environment becomes heavy.",

        "[BULLET] The Yellow Sari and Waist (Kaṭi-taṭa-pīta-dukūla): In yogic anatomy, the waist area corresponds to the lower structural energy centers—the Manipura Chakra (the solar plexus), which governs personal power, boundaries, and how we digest external aggression. Yellow is the literal cosmic color of this chakra.",

        "[BULLET] The Transformation (Mayūkha-Tiraskṛta): Anamika looks at this verse. She visualizes her own aura wrapped in this wondrous, golden, protective light (Vicitra-mayūkha). This is not an armor of angry defense, but an aura of such intense, blazing clarity and self-contained bliss that external negativity cannot pass through it.",

        "[BULLET] The Execution: Standing right there in the shared mud kitchen, Anamika's energy becomes so blindingly clear and luminous that it completely 'eclipses' (tiraskṛta) the cold, dim, and moody atmosphere (candra-ruce) generated by Mauna’s human conditioning. Anamika doesn't need to hide or fight; the sheer brilliance of her clean, unconditioned aura effortlessly recalibrates and clears the entire room's energy field from within.",

        "[HEADER]  प्रणतसुरासुरमौलिमणिस्फुरदंशुलसन्नखचन्द्ररुचे  — Tool for Anamika to dissolve her internal struggles with authority, rightness, ",
        "[BULLET]  The Equanimity of Gods and Demons (Surāsura):The gods (Suras) represent what Anamika considers 'correct, pure, and good.' The demons (Asuras) represent what she considers 'incorrect, messy, and toxic' (Mauna's behavior). In this line, both the gods and the demons are bowing down at the exact same feet of the Goddess. Anamika realizes that from the level of Pure Awareness, the rigid duality of 'good vs. bad members' or 'victim vs. perpetrator' dissolves completely. Both are just temporary shapes passing through the cosmic play.  ",

        "[BULLET]   The Crowns of Pride Touching the Ground (Mauli-Maṇi):The crowns represent the highest peak of ego and personal pride. When the gods and demons bow, their crowns touch the dust at Her feet. The flashing gems (Sphurad-aṃśu) represent all the flashing, hyperactive intellectual justifications Anamika's ego creates to prove she is right. She surrenders her own crown of 'being the perfect seeker' and drops it to the ground.",

        "[BULLET]  The Soothing Moonlight of the Feet (Nakha-Candra-Ruce): While the crowns are full of flashing, aggressive, scattered light (Sphurat), the Goddess's toenails emit a calm, cool, soothing moonlight (Candra-ruce). By grounding her attention at the feet of the Goddess, Anamika completely cools down her nervous system. She stops demanding that Mauna bow to her terms. Anamika stands in the kitchen, completely grounded, radiating a calm, non-judgmental stability that is so unshakeable that even the most 'demonic' friction in the room is naturally compelled to quiet down and rest. ",

        "[HEADER]  जितकनकचलमौलिमदोर्जित — unshakeable alignment tool for Anamika",
        "[BULLET]   Surpassing the Golden Mountain (Jita-Kanakācala): Mount Meru is the unshakeable center of the universe. By invoking this image, Anamika realizes that her true nature (I AM) is as solid, grand, and unmovable as a golden mountain peak. When Mauna displays 'incorrect' behavior or attempts to create environmental friction, Anamika checks her posture and internal state. She realizes: 'I am not a fragile ego that can be shaken by a flatmate's mood. I am rooted in the unshakeable center of my own awareness.' ",

        "[BULLET]  The Unrestrained Vital Force (Madoorjita-Nirbhara): Anamika stops wasting her vital energy on internal defensive dialogues, imaginary arguments, or passive-aggressive reactions. Instead, she gathers all that scattered energy and channels it into a concentrated, mighty spiritual presence. Her internal state becomes immensely strong but completely quiet. ",

        "[BULLET]  The Sovereignty of the Elephant Matrix (Kuñjara-Kumbha): A majestic elephant walks through a forest completely unbothered by the smaller creatures around it; it doesn't need to fight or defend its space because its sheer presence commands sovereignty. Anamika drops all petty desires to correct Mauna, to prove herself 'right,' or to seek validation. She steps into this elephant-like spiritual sovereignty. She cooks, moves, and shares the space with an aura of total abundance, completely neutralizing the room's tension by simply being an unshakeable mountain of peace. ",

    ],

    philosophy: [
        "Any Yin and Yang, be it good and bad, success and failure, or happiness and sadness, we as humans obviously strive for one and fear, hate, or avoid the other. It is this very resistance which causes us to enjoy the good only briefly, while for the majority of our lives we are actually resisting or ruminating over the other. Pursue Artha and Kama strictly as per Dharma, but surrender the fruits—whether they bring good or bad, sickness or health—at the feet of the Mother. She is the ultimate source of both; it is all Her Maya. Transcend and develop equanimity. Then, that surrender will reflect a calm, cool, soothing moonlight from the Mother's toenails, surpassing the absolute best of joys in this universe. This realization allows one to walk through life like a majestic elephant, rooted in our true nature of “I AM,” solid as the golden Meru Mountain, leading us eventually to our ultimate destination: Moksha"
    ],

    reflection: [
        "<strong>The Trap of Resistance (The Duality of Yin & Yang):</strong>  Human suffering doesn't come from bad experiences; it comes from our violent resistance (Dvesha) to them. In the kitchen, Anamika's energy drops because she is actively resisting the 'Yang' of Mauna’s conditioning while desperately craving a peaceful 'Yin' environment. This resistance means she can only enjoy peace briefly, spending the rest of her time ruminating.",

        "<strong>TThe Purusharthas Aligned with Dharma:</strong> Pursue Artha (material security/duties) and Kama (desire for comfort/peace) strictly as per Dharma, but surrender the fruits. Anamika has a functional duty to cook, share the room, and maintain her life. She executes these duties cleanly. But she releases her desperate attachment to the fruits of her actions (whether Mauna smiles at her or acts coldly). She surrenders the outcome completely.",

        "<strong>Surrendering the Crowns to the Moonlit Toenails (Line 16.2):</strong> This is the exact esoteric meaning of the Suras (gods/good) and Asuras (demons/bad) bowing together. They represent the two halves of duality. When Anamika surrenders both sides to the Mother, she is recognizing that both are just temporary waves of Maya. By grounding herself at the Mother’s feet, her consciousness catches the reflection of the soothing moonlight emitting from Her toenails (Lasannakha-candra-ruce). This moonlight is the cool, non-reactive space of Upeksha (Equanimity)—a deep, baseline bliss that completely surpasses the fleeting, temporary joys of worldly comfort.",

        "********",

        "<strong>The Unshakeable Meru & Majestic Elephant (Line 16.3):</strong> Once this surrender happens, Anamika’s identity shifts entirely. She realizes her true nature is 'I AM'—solid, unmovable, and grand like the Golden Mount Meru (Jita-kanakācala). She no longer feels small, fragile, or victimized by her environment. She stands in that traditional kitchen with the quiet, effortless sovereignty of a majestic elephant (Kuñjara), completely unbothered by external weather, walking her path steadily toward ultimate liberation (Moksha).",

         
    ],

    image1: "/images/maa/maaverse16.png",

    imagepnt: "/images/maa/maaverse16.png",


    stanzaData: [
        // Line 16.1: The Luminous protective Aura (Manipura Center)
        {
            sanskrit: "कटितटपीतदुकूल",
            meaning: "Wearing a fine, beautifully wrapped yellow silk sari around Your waist."
        },
        {
            sanskrit: "विचित्र",
            meaning: "Wondrously, intricately embroidered, and multicolored."
        },
        {
            sanskrit: "मयुखतिरस्कृतचन्द्ररुचे",
            meaning: "Whose blazing, radiant rays of light completely eclipse and outshine the luster of the moon."
        },

        // Line 16.2: Transcending Duality (The Surrender of Crowns)
        {
            sanskrit: "प्रणतसुरासुर",
            meaning: "Before whom both the gods (pure tendencies) and demons (egoic tendencies) bow down."
        },
        {
            sanskrit: "मौलिमणिस्फुरदंशु",
            meaning: "The proud crowns of their heads touching the ground, flashing and reflecting vivid rays of light."
        },
        {
            sanskrit: "लसन्नखचन्द्ररुचे",
            meaning: "Upon Your beautifully shining toenails, which radiate like pristine, cooling crescent moons."
        },

        // Line 16.3: Unshakeable Sovereign Abundance (The Golden Peak)
        {
            sanskrit: "जितकनकचलमौलि",
            meaning: "Surpassing the absolute majesty, stability, and grandeur of the golden peaks of Mount Meru."
        },
        {
            sanskrit: "मदोर्जितनिर्भर",
            meaning: "Overflowing with a mighty, unshakeable, and unrestrained vital spiritual force."
        },
        {
            sanskrit: "कुञ्जरकुम्भकुचे",
            meaning: "Radiating the majestic power and universal nourishment resembling the frontal lobes of a royal elephant."
        },

        // Line 16.4: The Triumphant Chorus of Inner Liberation
        {
            sanskrit: "जय जय हे",
            meaning: "Victory! Victory to You, the ultimate anchor of unshakeable clarity!"
        },
        {
            sanskrit: "महिषासुरमर्दिनि",
            meaning: "O Slayer of the buffalo demon Mahishasura (the reactive, judgmental ego)."
        },
        {
            sanskrit: "रम्यकपर्दिनिशैलसुते",
            meaning: "O Daughter of the unshakeable Mountain, adorned with beautifully braided, elegant tresses."
        }
    ],

};

export default verse16;
